// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDy9Cj0CTX2WCyix0sifBfPOYdapvVVW3k',
    appId: '1:867384450726:web:e594883d47b7f083df9e67',
    messagingSenderId: '867384450726',
    projectId: 'chartapp-d59ee',
    authDomain: 'chartapp-d59ee.firebaseapp.com',
    storageBucket: 'chartapp-d59ee.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1H8PZqbxgq2Z90860rOavkdQW3zxzxPA',
    appId: '1:867384450726:android:0d624a47f1b7b6bfdf9e67',
    messagingSenderId: '867384450726',
    projectId: 'chartapp-d59ee',
    storageBucket: 'chartapp-d59ee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7qJa7g8WSkJC5aMVS9qaeXbURrDncuu8',
    appId: '1:867384450726:ios:d1bd7b66dcae4f97df9e67',
    messagingSenderId: '867384450726',
    projectId: 'chartapp-d59ee',
    storageBucket: 'chartapp-d59ee.firebasestorage.app',
    iosBundleId: 'com.example.chartApp',
  );
}
